### numpy

In [3]:
import numpy as np

In [2]:
a=np.array([10,20,30,50,40,80,75])

In [3]:
a

array([10, 20, 30, 50, 40, 80, 75])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a.ndim   #dimensions of array

1

In [6]:
a.dtype  #datatype of array elements

dtype('int32')

In [7]:
b=np.array([10,20,30],np.int8)
b

array([10, 20, 30], dtype=int8)

In [8]:
b

array([10, 20, 30], dtype=int8)

In [9]:
b=np.array([10,20,46,550],np.int8)
b

array([10, 20, 46, 38], dtype=int8)

In [10]:
2**8-1

255

In [11]:
f=np.array([10.9,52,3,11.45])  #array with float values
f

array([10.9 , 52.  ,  3.  , 11.45])

In [12]:
f.dtype

dtype('float64')

In [16]:
print(type(f))
print(f.ndim)  #dimensions of the array
print(f.dtype) #data type of array elements
print(f.size)  #number of  array elements
print(f.shape)  #shape of the array
print(f.itemsize) #element size

<class 'numpy.ndarray'>
1
float64
4
(4,)
8


In [17]:
s=np.array([1,2,5,'hello'])
s

array(['1', '2', '5', 'hello'], dtype='<U11')

In [18]:
s.dtype

dtype('<U11')

In [19]:
#creating 2-d array
a=np.array([[1,5,4,6],[10,6,5,4]])
a

array([[ 1,  5,  4,  6],
       [10,  6,  5,  4]])

In [20]:
#creating array using range()

a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a=np.array(range(11,21))
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
# creating array using arange()

a=np.arange(4)
a

array([0, 1, 2, 3])

In [25]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
c=np.arange(1,11,2)   #start, stop,step 
c

array([1, 3, 5, 7, 9])

In [28]:
c=np.arange(2,11,2)
c

array([ 2,  4,  6,  8, 10])

In [31]:
d=np.arange(4,)
d

array([0, 1, 2, 3])

In [32]:
#creating array using linspace

a=np.linspace(1,10,20)  #with in given range,with given noofelements
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [33]:
b=np.logspace(1,10,20) #creating array in given range,with
#no of elements with their log values
b

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [35]:
np.full(10,'python')  #repeating for 10 times with given value

array(['python', 'python', 'python', 'python', 'python', 'python',
       'python', 'python', 'python', 'python'], dtype='<U6')

In [36]:
np.zeros(10)  #creating array with '0' for defined no of times

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.ones(20)   #creating array with '1' for defined no of times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [39]:
a=np.array([[1,2,3],[4,5,6]])  #2-d array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


In [41]:
a.ndim

2

In [42]:
a.size  #no of elements

6

In [43]:
a.itemsize

4

In [44]:
#creating 3-d array

a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,20,30]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 20, 30]]])

In [45]:
a.ndim

3

In [46]:
#accessing array elements

a=np.array([10,200,34,54,87])
a

array([ 10, 200,  34,  54,  87])

In [47]:
a[0]  #forward indexing

10

In [48]:
a[-1]  #backward indexing

87

In [49]:
a[-5]

10

In [50]:
a[::-1]

array([ 87,  54,  34, 200,  10])

In [51]:
# accessing 2-d elements

a=np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [52]:
a.shape

(2, 3)

In [53]:
a[0]

array([10, 20, 30])

In [54]:
a[1]

array([40, 50, 60])

In [55]:
a[0,1]  #row index,column index

20

In [56]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [57]:
a[1,2]

60

In [58]:
a[:,-1]

array([30, 60])

In [59]:
a[::-1]  #reverse order

array([[40, 50, 60],
       [10, 20, 30]])

In [60]:
a[:,-2]

array([20, 50])

In [62]:
# accessing 3-d array

a=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[15,45,65]]])
a

array([[[10, 20, 30],
        [40, 50, 60]],

       [[70, 80, 90],
        [15, 45, 65]]])

In [63]:
a[0]

array([[10, 20, 30],
       [40, 50, 60]])

In [64]:
a[1]

array([[70, 80, 90],
       [15, 45, 65]])

In [65]:
a[0][0]

array([10, 20, 30])

In [66]:
a[0][1]

array([40, 50, 60])

In [67]:
a[1][0]

array([70, 80, 90])

In [68]:
a[1][1]

array([15, 45, 65])

In [69]:
a[:,-1]

array([[40, 50, 60],
       [15, 45, 65]])

In [70]:
a[0][0][1]

20

In [73]:
a[::1]

array([[[10, 20, 30],
        [40, 50, 60]],

       [[70, 80, 90],
        [15, 45, 65]]])

In [74]:
a

array([[[10, 20, 30],
        [40, 50, 60]],

       [[70, 80, 90],
        [15, 45, 65]]])

In [75]:
a[:,1,2]

array([60, 65])

In [76]:
#shape

a=np.array([1,2,3,4])
b=np.array([[10,20,30,40],[50,60,70,80]])
c=np.array([[[1,2,3],[45,12,63]],[[54,85,45],[98,74,54]]])
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(2, 2, 3)


In [4]:
a=np.array([[[1,2,3],[10,20,30]],[[4,5,6],[7,8,9]]])
a            

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [ 7,  8,  9]]])

# 

In [79]:
a[0,0,1]

2

In [5]:
a

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [ 7,  8,  9]]])

In [6]:
#reshape of array

a=np.arange(1,21)

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
b=a.reshape(4,5) #2-d array
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
b=a.reshape(5,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [10]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [11]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [12]:
c=a.reshape(5,2,2)  #3-d array
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [13]:
c=a.reshape(2,5,2)
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [14]:
c=a.reshape(2,2,5)
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [16]:
# Iteration through an array

l=[10,90,78,65,4]
for i in l:
    print(i,end=" ")

10 90 78 65 4 

In [17]:
a=np.arange(1,5)  #1-d array
a

array([1, 2, 3, 4])

In [18]:
for i in a:
    print(i,end=" ")

1 2 3 4 

In [19]:
b=a.reshape(2,2)  #2-D array
b

array([[1, 2],
       [3, 4]])

In [20]:
for i in b:
    for j in i:
        print(j,end=" ")

1 2 3 4 

In [21]:
c=a.reshape(2,1,2)  #3D array
c

array([[[1, 2]],

       [[3, 4]]])

In [22]:
for i in c:
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 4 

In [27]:
#joining of arrays

a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [25]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [29]:
a=np.arange(1,5)
b=np.arange(6,10)
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [34]:
d=a.reshape(2,2)  #2-D array
e=b.reshape(2,2)
print(d)
print(e)
np.concatenate((d,e))  #joining e,d

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [35]:
g=a.reshape(2,1,2)  #3D array
h=b.reshape(2,1,2)
print(g)
print(h)
np.concatenate((g,h))

[[[1 2]]

 [[3 4]]]
[[[6 7]]

 [[8 9]]]


array([[[1, 2]],

       [[3, 4]],

       [[6, 7]],

       [[8, 9]]])

In [36]:
c

array([1, 2, 3, 4, 6, 7, 8, 9])

### ravel()--> creates copy of original array, if any modifications in duplicate array will make changes in original array
### flatten() --> creates copy of original array, if any modifications in duplicate array will not make any changes in original array

In [37]:
original=np.array([10,20,89,76])
original

array([10, 20, 89, 76])

In [38]:
copy=original.ravel()
copy

array([10, 20, 89, 76])

In [39]:
copy[0]=100

In [40]:
copy

array([100,  20,  89,  76])

In [41]:
original

array([100,  20,  89,  76])

In [43]:
a=np.array([100,200,304,516])
a

array([100, 200, 304, 516])

In [44]:
copy1=a.flatten()
copy1

array([100, 200, 304, 516])

In [45]:
copy1[2]=3000

In [46]:
copy1

array([ 100,  200, 3000,  516])

In [47]:
a

array([100, 200, 304, 516])

### statistical and mathematical operations in numpy

In [49]:
np.min(a)    # smallest element of array

100

In [50]:
np.max(a)  # largest element of array

516

In [54]:
a.argmin()  # index of smallest element

0

In [55]:
a.argmax()  #index of largest element

3

In [56]:
a.mean()  #mean of array elements

280.0

In [57]:
np.median(a)  #median of array elements

252.0

In [58]:
np.var(a)   #variance of array elements

23768.0

In [59]:
np.std(a)  #standard deviation of array elements

154.16873872481412

In [60]:
np.sqrt(a)  #squareroot of array elements

array([10.        , 14.14213562, 17.43559577, 22.71563338])

In [61]:
np.sum(a)  #sum of all array elements

1120

AxisError: axis 1 is out of bounds for array of dimension 1

In [63]:
a

array([100, 200, 304, 516])

In [66]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [67]:
np.sin(a)

array([-0.50636564, -0.8732973 ,  0.6702068 ,  0.70242924])

In [68]:
np.cos(a)

array([ 0.86231887,  0.48718768, -0.7421744 ,  0.71175358])

In [69]:
np.tan(a)

array([-0.58721392, -1.79252748, -0.90303142,  0.98689948])

In [70]:
np.log(a)

array([4.60517019, 5.29831737, 5.7170277 , 6.24610677])

In [72]:
np.log10(a) #logarthmic values with base 10

array([2.        , 2.30103   , 2.48287358, 2.7126497 ])

In [73]:
np.multiply(a,3) #multiply each element with given number

array([ 300,  600,  912, 1548])

In [74]:
np.divide(a,10)  #divides each element with given number

array([10. , 20. , 30.4, 51.6])

In [76]:
np.mod(a,3)

array([1, 2, 1, 0], dtype=int32)

In [78]:
np.remainder(a,10)

array([0, 0, 4, 6], dtype=int32)

In [79]:
np.dot(a,5)  #dot product

array([ 500, 1000, 1520, 2580])

### stacking -- organizing & arranging elements in an order

In [80]:
np.hstack(a)   #horizontal stacking

array([100, 200, 304, 516])

In [89]:
b=np.arange(4)
c=np.vstack((a,b))
c               #vertical stack

array([[100, 200, 304, 516],
       [  0,   1,   2,   3]])

In [88]:
aa=np.hstack(a)
c=np.hstack((aa,b))
c

array([100, 200, 304, 516,   0,   1,   2,   3])

In [91]:
#filtering array

a=np.array([10,24,54,21,65,48])
b=[False,True,False,True,True,True]
c=a[b]
c

array([24, 21, 65, 48])

In [92]:
# print array elements greater than 25

b=[]
for i in a:
    if i>25:
        b.append(True)
    else:
        b.append(False)
c=a[b]
c  

array([54, 65, 48])

### random()

In [97]:
import random
a=np.random.randint(20)   #returns integer value randomly in given range
a

18

In [98]:
np.random.randn()  #float values

-0.1452353740099727

In [99]:
np.random.randn(10)

array([ 0.58926382,  0.42281626,  0.40005631, -0.75877401, -1.1242535 ,
        2.26109388, -0.41340004,  1.24400289, -1.07220571, -0.59709053])

In [100]:
a=np.random.randint(100,size=(20))  #1D  #range,size
a

array([50, 44, 39, 20,  5, 47, 26, 53, 39, 64,  6, 18, 64, 87, 75, 66, 80,
       56, 31, 21])

In [103]:
a=np.random.randint(200,size=(4,5))  #2D array
a

array([[104,  62, 118,  75,  87],
       [ 87, 161, 123, 122,  60],
       [ 46, 122, 175,  93, 153],
       [ 11,   3, 159,  87, 192]])

In [104]:
a=np.random.randint(50,size=(2,5,2)) #3D array
a

array([[[33, 26],
        [37, 22],
        [48, 36],
        [17, 16],
        [ 7, 27]],

       [[46,  8],
        [35, 22],
        [28,  2],
        [40, 14],
        [39, 46]]])

In [106]:
np.random.choice([10,23,4,5,90,87])

90

In [111]:
np.random.choice([10,23,4,5,90,87],size=(3,2)) #2D

array([[10,  5],
       [10, 90],
       [90, 10]])

In [108]:
np.random.choice([10,23,4,5,90,87],size=(3,2,1))  #3D

array([[[ 4],
        [90]],

       [[87],
        [90]],

       [[23],
        [90]]])

In [109]:
np.random.shuffle(a)

In [110]:
np.random.normal() #normal distribution

-4.1862310257805

In [114]:
a=np.array([[1,2,3],[4,5,6]])
a



array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
b=a.T  #Transpose
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
np.power(a,4)

array([[   1,   16,   81],
       [ 256,  625, 1296]], dtype=int32)